### PR TITLE
Adding image support

### PR DESCRIPTION
**Pull request by Roshyo**
| Q               | A
| --------------- | -----
| Branch?         | master
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | yes
| Deprecations?   | no

Created a new Sitemap Interface for images support, added link in SitemapUrl.
Created Twig macro to display images tags

Also added a spaceless tag in twig to minify the XML (just a little bit faster to download :) )

### CODE REVIEW

**Comment by stefandoorn** [comment]
Are you able to provide tests & split the `spaceless` change into a separate PR? It's quite some code to review, so the smaller the better :-)

**Comment by Roshyo** [comment]
I've removed the spaceless changes. I'll redo them after this PR is merge.

I'll try to add tests but I have no idea where to begin.

**Comment by Roshyo** [comment]
Here we are ?
However, this coveralls decrease seems really high... What can I do to limit it ?

**Comment by stefandoorn** [comment]
@Roshyo I will try to look at it soon.

**Comment by stefandoorn** [comment]
Superseded by #61. Thanks @Roshyo!

**Pull request closed without merging**
