### PR TITLE
Update routing.yml

### PR DESCRIPTION
**Pull request by SquareInnov**
FIX Routes redirections

### CODE REVIEW

**Comment by SquareInnov** [comment]
CVE patched in api-platform/core v2.7, Sylius 1.12 require currently api-platform/core v2.6. But Sylius 1.13 will require api-platform/core v2.6, so this pull request will build succefully

**Comment by stefandoorn** [comment]
I will see if I can update some things in `master`, so we can rebase this branch and get it merged.

**Comment by stefandoorn** [comment]
Oh.. Sylius 1.13 is not released yet :-(

**Comment by stefandoorn** [comment]
Change itself looks like something that had to be updated already a long time ago, also previous Symfony versions required it this way.

**Pull request merged**
