### PR TITLE
Add compatibility to Symfony 5

### PR DESCRIPTION
**Pull request by lruozzi9**
Hi! These changes will solve issue #148 and provide compatibility to Symfony 5 used by Sylius 1.9.

### CODE REVIEW

**Comment by mdhgriffiths** [comment]
What a timely pull request! Just random stranger here, but wanted to share that with these changes I still ran into an exception:

```
Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Too few arguments to function Symfony\Component\Config\Definition\Builder\TreeBuilder::__construct(), 0 passed in /srv/sylius/vendor/stefandoorn/sitemap-plugin/src/DependencyInjection/Configuration.php on line 18 and at least 1 expected in /srv/sylius/vendor/symfony/config/Definition/Builder/TreeBuilder.php:26
Stack trace:
#0 /srv/sylius/vendor/stefandoorn/sitemap-plugin/src/DependencyInjection/Configuration.php(18): Symfony\Component\Config\Definition\Builder\TreeBuilder->__construct()
#1 /srv/sylius/vendor/symfony/config/Definition/Processor.php(50): SitemapPlugin\DependencyInjection\Configuration->getConfigTreeBuilder()
#2 /srv/sylius/vendor/symfony/dependency-injection/Extension/Extension.php(111): Symfony\Component\Config\Definition\Processor->processConfiguration(Object(SitemapPlugin\DependencyInjection\Configuration), Array)
#3 /srv/sylius/vendor/stefandoorn/sitemap-plugin/src/DependencyInjection/SitemapExtension.php(23): Symfony\Component in /srv/sylius/vendor/symfony/config/Definition/Builder/TreeBuilder.php on line 26
```

[So far] I got around this by updating [`SitemapPlugin\DependencyInjection`](https://github.com/stefandoorn/sitemap-plugin/blob/master/src/DependencyInjection/Configuration.php) to use this updated code:

```diff
    public function getConfigTreeBuilder()
    {
-        $treeBuilder = new TreeBuilder();
-        $rootNode = $treeBuilder->root('sylius_sitemap');
+        $treeBuilder = new TreeBuilder('sylius_sitemap');
+        /** @var ArrayNodeDefinition $rootNode */
+        $rootNode = $treeBuilder->getRootNode();

        $this->addSitemapSection($rootNode);

        return $treeBuilder;
    }
```

**Comment by stefandoorn** [comment]
Will have a look soon!

**Comment by stefandoorn** [comment]
@mdhgriffiths Will push a change for this to `master` soon.

**Comment by stefandoorn** [comment]
Thanks!

**Pull request merged**
