### PR TITLE
Sylius 1.12 updates

### PR DESCRIPTION
**Pull request by jmwill86**
Untested changes to upgrade to Sylius 1.12

### CODE REVIEW

**Comment by stefandoorn** [comment]
Thanks @jmwill86 

Can you also add it to the build matrix so CI also tests this new version?

https://github.com/stefandoorn/sitemap-plugin/blob/master/.github/workflows/build.yml#L26

**Comment by stefandoorn** [comment]
I've pushed some changes to master so everyone can at least install using Sylius v1.12 from `dev-master` - but build still red on all kind of errors.. that still needs a bit of a look into.

**Comment by jakubtobiasz** [comment]
Hi @stefandoorn!
In `ecs.php` change `ContainerConfigurator` type to ECSConfig. It will fix your error :).

**Comment by stefandoorn** [comment]
Thanks!

**Comment by andriusvo** [comment]
@stefandoorn any plans to merge?

**Comment by jmwill86** [comment]
I did put some time into this a while ago but if I remember there were conflicting packages that made the version constraints testing matrix difficult/impossible. I think we may need a major version bump, but it's a while since I've looked into this.

**Comment by stefandoorn** [comment]
I only added v1.12 back then to the matrix, as there were too many conflicts and issues arising with the previous versions. So for then I decided only to test with the latest Sylius version, and maybe try to add older versions back into the matrix and see what happens. 

Most of the changes in this PR have been implemented already, so I think we can close this one. For sure thanks for the suggestions, as they have been applied separately. 

Hope we can add some PR's to add e.g. Sylius v1.11 again and maybe Symfony 6.

**Pull request closed without merging**
