### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by SquareInnov**
Allow next major Sylius version 1.13

### CODE REVIEW

**Comment by stefandoorn** [comment]
Thanks, @SquareInnov - can you also change it in the test set-up so we ensure the tests also run against Sylius 1.13?

https://github.com/stefandoorn/sitemap-plugin/blob/master/.github/workflows/build.yml

**Comment by stefandoorn** [comment]
Not really sure though why CI does not run.. :D

**Comment by SquareInnov** [comment]
Done, Regarding to this : 
https://github.com/Sylius/Sylius/blob/1.13/UPGRADE-1.13.md

I bump php version and add new symfony version to the file

**Comment by SquareInnov** [comment]
> Not really sure though why CI does not run.. :D

I don't know, the branch is not excluded

**Comment by stefandoorn** [comment]
I have enabled Builds/CI again. Will check / test the PR later this week. Does it already work with the beta of 1.13 as well with this change, or won't this be in effect anyhow until 1.13 is officially released?

**Comment by SquareInnov** [comment]
> I have enabled Builds/CI again. Will check / test the PR later this week. Does it already work with the beta of 1.13 as well with this change, or won't this be in effect anyhow until 1.13 is officially released?

No, it will work on the the release of the 1.13, I think.

**Comment by stefandoorn** [comment]
Merging this and if something pops up in CI, I'll look into that. Thanks!

**Pull request merged**
