### PR TITLE
Make StaticUrlProvider more clever

### PR DESCRIPTION
**Pull request by sweoggy**
| Q               | A
| --------------- | -----
| Branch?         | master
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | #26, #27 
| License         | MIT

- Use channel locales for creating site map URL if no locales are specified in config

### CODE REVIEW

**Comment by sweoggy** [comment]
The confirmation links should probably be fixed for the other provides as well, but that should probably be done in a separate commit

**Comment by stefandoorn** [comment]
What do you mean with confirmation links?

**Comment by sweoggy** [comment]
According to Google each localised link should be present in the sitemap, and then each hreflang should reference the other localised links, "confirming" them.

Example:
```
        <url>
            <loc>https://www.persiennbutiken.se/nya/sv_SE/</loc>
            <xhtml:link rel="alternate" hreflang="en" href="https://www.persiennbutiken.se/nya/en_GB/"/>                       
            <changefreq>weekly</changefreq>
            <priority>0.3</priority>
        </url>
        <url>
            <loc>https://www.persiennbutiken.se/nya/en_GB/</loc>
            <xhtml:link rel="alternate" hreflang="sv" href="https://www.persiennbutiken.se/nya/sv_SE/"/>                         
            <changefreq>weekly</changefreq>
            <priority>0.3</priority>
        </url>
```

**Comment by stefandoorn** [comment]
Ah, I see now. That's a good point. Should be fixed separate indeed, because maybe we can fix that more at view level (or other method) than at the provider level. Would make the providers more complex.

**Comment by stefandoorn** [comment]
So maybe it's better to take that part out of this PR and in here only focus on supporting the other locales at all, then later we fix this issue in another PR.

**Comment by sweoggy** [comment]
On mobile, didn't mean to close it 😁

I agree, I will adjust this PR after #27 is merged

**Comment by stefandoorn** [comment]
Can you still look into this one @sweoggy ?

**Comment by sweoggy** [comment]
@stefandoorn what about now?

**Comment by sweoggy** [comment]
I am working on extending the tests, not ready yet

**Pull request merged**
